"""hospitals table

Revision ID: 1b105eeb69f9
Revises: fddb0e7d4e44
Create Date: 2026-07-20 22:27:12.797309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b105eeb69f9'
down_revision = 'fddb0e7d4e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hospitals'))
    )
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospitals_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospitals_name'))

    op.drop_table('hospitals')
    # ### end Alembic commands ###
