"""delete cascade

Revision ID: 4f8a3382851b
Revises: f5d0e2761ee7
Create Date: 2026-07-23 02:14:05.226096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8a3382851b'
down_revision = 'f5d0e2761ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments_installations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_equipments_installations_equipment_id_equipments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_equipments_installations_installation_id_installations'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_equipments_installations_installation_id_installations'), 'installations', ['installation_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_equipments_installations_equipment_id_equipments'), 'equipments', ['equipment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_installations_hospital_id_hospitals'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_installations_hospital_id_hospitals'), 'hospitals', ['hospital_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tokens_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tokens_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users_installations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_installations_installation_id_installations'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_users_installations_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_installations_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_users_installations_installation_id_installations'), 'installations', ['installation_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_installations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_installations_installation_id_installations'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_users_installations_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_installations_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_users_installations_installation_id_installations'), 'installations', ['installation_id'], ['id'])

    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tokens_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tokens_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_installations_hospital_id_hospitals'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_installations_hospital_id_hospitals'), 'hospitals', ['hospital_id'], ['id'])

    with op.batch_alter_table('equipments_installations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_equipments_installations_equipment_id_equipments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_equipments_installations_installation_id_installations'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_equipments_installations_installation_id_installations'), 'installations', ['installation_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_equipments_installations_equipment_id_equipments'), 'equipments', ['equipment_id'], ['id'])

    # ### end Alembic commands ###
