"""services table

Revision ID: 928aafa9adcc
Revises: 9d5a1d2056dc
Create Date: 2026-07-29 15:59:21.123375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928aafa9adcc'
down_revision = '9d5a1d2056dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parts'))
    )
    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opened_date', sa.DateTime(), nullable=True),
    sa.Column('closed_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('problem_description', sa.String(length=1000), nullable=True),
    sa.Column('fix_description', sa.String(length=1000), nullable=True),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], name=op.f('fk_services_equipment_id_equipments')),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_services_hospital_id_hospitals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_hospital_id'), ['hospital_id'], unique=False)

    op.create_table('service_parts',
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_service_parts_part_id_parts')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_service_parts_service_id_services')),
    sa.PrimaryKeyConstraint('service_id', 'part_id', name=op.f('pk_service_parts'))
    )
    op.create_table('users_services',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_users_services_service_id_services')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_services_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'service_id', name=op.f('pk_users_services'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_services')
    op.drop_table('service_parts')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_services_equipment_id'))

    op.drop_table('services')
    op.drop_table('parts')
    # ### end Alembic commands ###
