"""user_phone_numbers, categories, parameters, equipments_parameters, hospital_contacts...

Revision ID: 9d5a1d2056dc
Revises: 4f8a3382851b
Create Date: 2026-07-29 14:45:21.033759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5a1d2056dc'
down_revision = '4f8a3382851b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_equipments')
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ownership_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_equipments_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_equipments_category_id_categories'), 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('equipments_installations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('removed_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('warranty_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('warranty_end_date', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_equipments_installations_equipment_id_equipments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_equipments_installations_installation_id_installations'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_equipments_installations_installation_id_installations'), 'installations', ['installation_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_equipments_installations_equipment_id_equipments'), 'equipments', ['equipment_id'], ['id'])

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))

    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installation_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('note', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_installations_hospital_id_hospitals'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_installations_hospital_id_hospitals'), 'hospitals', ['hospital_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('date_of_hire', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_of_termination', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users_installations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_installations_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_users_installations_installation_id_installations'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_installations_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_users_installations_installation_id_installations'), 'installations', ['installation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_installations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_installations_installation_id_installations'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_users_installations_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_installations_installation_id_installations'), 'installations', ['installation_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_users_installations_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('date_of_termination')
        batch_op.drop_column('date_of_hire')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_installations_hospital_id_hospitals'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_installations_hospital_id_hospitals'), 'hospitals', ['hospital_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('status')
        batch_op.drop_column('note')
        batch_op.drop_column('installation_type')

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('equipments_installations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_equipments_installations_equipment_id_equipments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_equipments_installations_installation_id_installations'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_equipments_installations_installation_id_installations'), 'installations', ['installation_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_equipments_installations_equipment_id_equipments'), 'equipments', ['equipment_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('warranty_end_date')
        batch_op.drop_column('warranty_start_date')
        batch_op.drop_column('removed_date')

    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_equipments_category_id_categories'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_equipments_category_id'))
        batch_op.drop_column('status')
        batch_op.drop_column('ownership_type')
        batch_op.drop_column('category_id')
        batch_op.drop_column('model')

    op.create_table('_alembic_tmp_equipments',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=255), nullable=True),
    sa.Column('model', sa.VARCHAR(length=64), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('ownership_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('status', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_equipments_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipments'))
    )
    # ### end Alembic commands ###
