"""installations table

Revision ID: f5d0e2761ee7
Revises: 1b105eeb69f9
Create Date: 2026-07-21 22:55:13.031873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d0e2761ee7'
down_revision = '1b105eeb69f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('install_date', sa.DateTime(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_installations_hospital_id_hospitals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installations'))
    )
    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installations_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installations_install_date'), ['install_date'], unique=False)

    op.create_table('equipments_installations',
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('installation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], name=op.f('fk_equipments_installations_equipment_id_equipments')),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], name=op.f('fk_equipments_installations_installation_id_installations')),
    sa.PrimaryKeyConstraint('equipment_id', 'installation_id', name=op.f('pk_equipments_installations'))
    )
    op.create_table('users_installations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('installation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], name=op.f('fk_users_installations_installation_id_installations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_installations_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'installation_id', name=op.f('pk_users_installations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_installations')
    op.drop_table('equipments_installations')
    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installations_install_date'))
        batch_op.drop_index(batch_op.f('ix_installations_hospital_id'))

    op.drop_table('installations')
    # ### end Alembic commands ###
