"""equipments table

Revision ID: fddb0e7d4e44
Revises: 35c1c3fb66c2
Create Date: 2026-07-18 00:16:29.724169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fddb0e7d4e44'
down_revision = '35c1c3fb66c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipments'))
    )
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipments_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipments_serial_number'), ['serial_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipments_serial_number'))
        batch_op.drop_index(batch_op.f('ix_equipments_name'))

    op.drop_table('equipments')
    # ### end Alembic commands ###
